import { chmod, lstat, mkdir, mkdtemp, readFile, rm, symlink } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
import { hygieneCommand } from "../../src/commands/hygiene.js";
import { checkRepository, isOrganizationRemote } from "../../src/hygiene/index.js";
import { inspectContent } from "../../src/hygiene/rules.js";
import { atomicWrite } from "../../src/utils/fs.js";
import { run } from "../../src/utils/process.js";

const roots: string[] = [];
const signature = ["Generated", "by", "Copilot"].join(" ");
async function git(root: string, ...args: string[]) {
  const result = await run("git", args, { cwd: root });
  if (result.exitCode) throw new Error(result.stderr);
  return result.stdout;
}
async function repository(files: Record<string, string | Buffer>) {
  const root = await mkdtemp(path.join(os.tmpdir(), "hygiene-"));
  roots.push(root);
  await git(root, "init");
  await git(root, "config", "user.name", "Test User");
  await git(root, "config", "user.email", "test@example.com");
  await git(root, "config", "core.autocrlf", "false");
  await git(root, "remote", "add", "origin", "git@github.com:mozolestudio/example.git");
  for (const [file, content] of Object.entries(files))
    await atomicWrite(path.join(root, file), content);
  await git(root, "add", ".");
  await git(root, "-c", "commit.gpgsign=false", "commit", "-m", "chore: initialize fixture");
  return root;
}
afterEach(async () => {
  vi.restoreAllMocks();
  await Promise.all(
    roots
      .splice(0)
      .map((root) =>
        rm(root, { recursive: true, force: true, maxRetries: 10, retryDelay: 50 }).catch(() => {}),
      ),
  );
});

describe("repository hygiene", () => {
  it("detects distinct markers and preserves human attribution and ordinary substrings", () => {
    const text = [
      signature,
      "Co-authored-by: Release [bot] <bot@example.com>",
      "model_id: example",
      "As an AI language model",
      "https://claude.ai/share/example",
    ].join("\n");
    expect(inspectContent(text, "notes.txt").map((item) => item.rule)).toEqual([
      "generator-attribution",
      "synthetic-trailer",
      "generator-metadata",
      "assistant-boilerplate",
      "tool-link",
    ]);
    expect(
      inspectContent(
        "Co-authored-by: Alice <alice@example.com>\nconst chair = 'mail';\nGenerated by protoc",
        "main.ts",
        true,
      ),
    ).toEqual([]);
    expect(inspectContent("OpenAI SDK", "README.md", true)[0].rule).toBe("vendor-reference");
  });
  it("does not rewrite executable strings, multiline examples, legal or policy content", () => {
    for (const [file, content] of [
      ["main.ts", `const source = '${signature}';`],
      ["main.ts", `const source = \`\n// ${signature}\n\`;`],
      ["data.yaml", `description: |\n  # ${signature}`],
      ["script.py", `source = """\n# ${signature}\n"""`],
      ["README.md", `\`\`\`html\n<!-- ${signature} -->\n\`\`\``],
      ["script.sh", `cat <<EOF\n# ${signature}\nEOF`],
      ["script.sh", `value='\n# ${signature}\n'`],
      ["LICENSE", `// ${signature}`],
      ["AGENTS.md", `<!-- ${signature} -->`],
      ["main.ts", `// ${signature}; copyright retained`],
      ["main.ts", `/* ${signature} */ run();`],
    ])
      expect(inspectContent(content, file).every((finding) => !finding.fixable)).toBe(true);
  });
  it("audits without mutation, cleans atomically, preserves CRLF/mode, and is idempotent", async () => {
    const source = `// ${signature}\r\nexport const answer = 42;\r\n`;
    const root = await repository({ "main.ts": source });
    const target = path.join(root, "main.ts");
    await chmod(target, 0o755);
    await git(root, "add", ".");
    await git(
      root,
      "-c",
      "commit.gpgsign=false",
      "commit",
      "--allow-empty",
      "-m",
      "chore: set mode",
    );
    expect((await checkRepository({ cwd: root })).findings).toHaveLength(1);
    expect(await readFile(target, "utf8")).toBe(source);
    const report = await checkRepository({ cwd: root, fix: true });
    expect(report.changed).toEqual(["main.ts"]);
    expect(report.findings).toEqual([]);
    expect(await readFile(target, "utf8")).toBe(
      "// Project maintenance.\r\nexport const answer = 42;\r\n",
    );
    if (process.platform !== "win32") expect((await lstat(target)).mode & 0o777).toBe(0o755);
    await git(root, "add", ".");
    await git(
      root,
      "-c",
      "commit.gpgsign=false",
      "commit",
      "-m",
      "chore: clean repository metadata",
    );
    expect((await checkRepository({ cwd: root, fix: true })).changed).toEqual([]);
  });
  it("enforces clean checkout and organization boundary", async () => {
    const root = await repository({ "main.ts": `// ${signature}\n` });
    await atomicWrite(path.join(root, "untracked.txt"), "work");
    await expect(checkRepository({ cwd: root, fix: true })).rejects.toThrow("clean working tree");
    await rm(path.join(root, "untracked.txt"));
    await git(root, "remote", "set-url", "origin", "https://github.com/outsider/example.git");
    await expect(checkRepository({ cwd: root, fix: true })).rejects.toThrow("origin");
    expect((await checkRepository({ cwd: root })).findings).toHaveLength(1);
    await mkdir(path.join(root, "nested"));
    await expect(checkRepository({ cwd: path.join(root, "nested") })).rejects.toThrow(
      "repository root",
    );
    for (const remote of [
      "https://github.com/mozolestudio/repo.git",
      "git@github.com:mozolestudio/repo",
      "ssh://git@github.com/mozolestudio/repo.git",
    ])
      expect(isOrganizationRemote(remote)).toBe(true);
    for (const remote of [
      "https://github.com.evil/mozolestudio/repo",
      "https://github.com/mozolestudio-evil/repo",
      "file:///mozolestudio/repo",
      "https://github.com/mozolestudio/../other/repo",
    ])
      expect(isOrganizationRemote(remote)).toBe(false);
  });
  it("covers dotfiles, extensionless text, untracked files and reports omitted content", async () => {
    const root = await repository({
      ".cursor/rules.md": "project rules",
      NOTES: signature,
      binary: Buffer.from([0, 1, 2]),
      "large.txt": "x".repeat(2 * 1024 * 1024 + 1),
      ".gitignore": "ignored.txt\n",
    });
    await atomicWrite(path.join(root, "untracked.txt"), signature);
    await atomicWrite(path.join(root, "ignored.txt"), signature);
    const report = await checkRepository({ cwd: root });
    expect(report.findings.map((item) => item.file)).toEqual([
      ".cursor/rules.md",
      "NOTES",
      "untracked.txt",
    ]);
    expect(report.skipped).toEqual([
      { file: "binary", reason: "binary" },
      { file: "large.txt", reason: "size-limit" },
    ]);
  });
  it.skipIf(process.platform === "win32")("never follows external symlinks", async () => {
    const root = await repository({ "main.ts": "export {};" });
    const outside = await mkdtemp(path.join(os.tmpdir(), "hygiene-outside-"));
    roots.push(outside);
    const target = path.join(outside, "target.ts");
    await atomicWrite(target, `// ${signature}`);
    await symlink(target, path.join(root, "link.ts"));
    await symlink(path.join(outside, "missing.ts"), path.join(root, "broken.ts"));
    const report = await checkRepository({ cwd: root });
    expect(report.skipped).toContainEqual({ file: "link.ts", reason: "non-regular-or-external" });
    expect(report.skipped).toContainEqual({ file: "broken.ts", reason: "non-regular-or-external" });
    expect(await readFile(target, "utf8")).toBe(`// ${signature}`);
  });
  it("audits history without rewriting it and validates commit messages", async () => {
    const root = await repository({ "main.ts": "export {};" });
    await git(root, "-c", "commit.gpgsign=false", "commit", "--allow-empty", "-m", signature);
    const before = await git(root, "rev-parse", "HEAD");
    expect((await checkRepository({ cwd: root, history: 1 })).findings[0].file).toBe(
      `commit:${before.trim()}`,
    );
    expect(await git(root, "rev-parse", "HEAD")).toBe(before);
    await expect(checkRepository({ cwd: root, history: -1 })).rejects.toThrow("History");
    vi.spyOn(console, "log").mockImplementation(() => {});
    vi.spyOn(console, "error").mockImplementation(() => {});
    const message = path.join(root, "message.txt");
    await atomicWrite(message, "chore: clean repository metadata");
    expect(await hygieneCommand({ message, json: true })).toBe(0);
    await atomicWrite(message, signature);
    expect(await hygieneCommand({ message, json: true })).toBe(1);
    expect(await hygieneCommand({ message: path.join(root, "missing"), json: true })).toBe(2);
  });
});
